name: Test Security Hook

on:
  push:
    branches: [ main ]
    paths:
      - 'examples/hooks/security_demo.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/hooks/security_demo.py'
  workflow_dispatch:

jobs:
  test-security-hook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Test security hook with safe command
        run: |
          echo '{"tool_name": "Bash", "tool_input": {"command": "echo hello"}}' | python3 examples/hooks/security_demo.py
          echo "Exit code: $?"
          
      - name: Test security hook with API key (should block)
        run: |
          set +e
          echo '{"tool_name": "Bash", "tool_input": {"command": "export OPENAI_API_KEY=sk-1234567890abcdef1234567890abcdef1234567890abcdef12"}}' | python3 examples/hooks/security_demo.py
          exit_code=$?
          echo "Exit code: $exit_code"
          if [ $exit_code -eq 2 ]; then
            echo "✅ Security hook correctly blocked API key"
          else
            echo "❌ Security hook failed to block API key"
            exit 1
          fi
          
      - name: Test security hook with Anthropic key (should block)
        run: |
          set +e
          echo '{"tool_name": "Bash", "tool_input": {"command": "export ANTHROPIC_API_KEY=sk-ant-api03-1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef12R"}}' | python3 examples/hooks/security_demo.py
          exit_code=$?
          echo "Exit code: $exit_code"
          if [ $exit_code -eq 2 ]; then
            echo "✅ Security hook correctly blocked Anthropic key"
          else
            echo "❌ Security hook failed to block Anthropic key"
            exit 1
          fi
          
      - name: Test security hook with AWS key (should block)
        run: |
          set +e
          echo '{"tool_name": "Bash", "tool_input": {"command": "export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE"}}' | python3 examples/hooks/security_demo.py
          exit_code=$?
          echo "Exit code: $exit_code"
          if [ $exit_code -eq 2 ]; then
            echo "✅ Security hook correctly blocked AWS key"
          else
            echo "❌ Security hook failed to block AWS key"
            exit 1
          fi
          
      - name: Test security hook with malformed JSON (should reject)
        run: |
          set +e
          echo '{"tool_name": "Bash", "tool_input": {"command": "echo hello}' | python3 examples/hooks/security_demo.py
          exit_code=$?
          echo "Exit code: $exit_code"
          if [ $exit_code -eq 1 ]; then
            echo "✅ Security hook correctly rejected malformed JSON"
          else
            echo "❌ Security hook failed to reject malformed JSON"
            exit 1
          fi